#!/bin/bash
 
workspaces () {
    no=0

    f1=$(wmctrl -d | sed -n '1p' | grep "*" | tail -c 2)
    f2=$(wmctrl -d | sed -n '2p' | grep "*" | tail -c 2)
    f3=$(wmctrl -d | sed -n '3p' | grep "*" | tail -c 2)
    f4=$(wmctrl -d | sed -n '4p' | grep "*" | tail -c 2)
    f5=$(wmctrl -d | sed -n '5p' | grep "*" | tail -c 2)

    echo "(box    :orientation 'h'"
    echo "        :space-evenly 'true'"
    echo "        :class 'workspaces'"
    echo "        :spacing 5"
    echo "                (button :onclick 'wmctrl -s 0'"
    echo "                        :class '$no$f1'"
    echo "                        (label  :text '1'))"
    echo "                (button :onclick 'wmctrl -s 1'"
    echo "                        :class '$no$f2'"
    echo "                        (label  :text '2'))"
    echo "                (button :onclick 'wmctrl -s 2'"
    echo "                        :class '$no$f3'"
    echo "                        (label  :text '3'))"
    echo "                (button :onclick 'wmctrl -s 3'"
    echo "                        :class '$no$f4'"
    echo "                        (label  :text '4'))"
    echo "                (button :onclick 'wmctrl -s 4'"
    echo "                        :class '$no$f5'"
    echo "                        (label  :text '5')))"
}

workspaces
