#! /bin/sh

xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
picom --experimental-backends --config $HOME/.config/picom/picom-herb.conf &
feh --bg-tile $HOME/.config/bspwm/tile.png &
eww open topbar &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          22

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#3c3836'
bspc config normal_border_color '#282828'


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
