#!/bin/bash

musicstats () {
    if [[ $(mpc status) == *"[playing]"* ]]; then
        echo ""
    else
        echo ""
    fi
}

curtime () {
    if [[ ! -f $HOME/.config/tmp/mpdtmp.zyx ]]; then
        echo "0"
    else
        mpc status %percenttime% | sed 's/ //g' | sed 's/%//g'
    fi
}

case $1 in
    toggle)
        musicstats
    ;;
    cur)
        curtime
    ;;
    curm)
        if [[ ! -f $HOME/.config/tmp/mpdtmp.zyx ]]; then
            echo "Not Playing"
        else
            mpc current | sed 's/.mp3//g'
        fi
    ;;
esac
